### ISSUE TITLE
Per-antenna UVW decomposition fails when time!=time_centroid

### ISSUE THREAD

**Issue by JSKenyon** [ska-sa/montblanc#248]
I encountered this when simulating data into a real (used) measurement set. UVW coordinates are consistent with the TIME_CENTROID column, not the TIME column. Consequently, it may not be possible to generate a consistent per-antenna UVW decomposition. 

The way to get around this is to use a per-baseline phase term and use the UVW coordinates directly from the MS. I think this is the safer option in general, even if it does mean a bit of a performance loss. I think it would be possible to support both modes of operation i.e. check for a valid decomposition and only resort to a per-baseline term if the decomposition turns out to be inconsistent. 

Mentioning @o-smirnov, in case he wants to make recommendations. This is semi-urgent as real data will often have this problem.

**Comment by sjperkins** [comment]
Yeah, I think its becoming evident that for real data, montblanc can't get away with this much longer.

I don't disagree that the change needs to be made, the question is where we're going to make it: `master` branch or the `dask` version. I would prefer the dask version since everything about it is going to be more flexible and it should be much easier to wrap data than the SourceProvider version. We should probably discuss everyone's timelines in a meeting.

@saiyanprince  Which version are you going to iterate on?

**Comment by saiyanprince** [comment]
@sjperkins I am currently working with the SourceProvider version, but I am quite happy to use the dask version going further.

**Comment by sjperkins** [comment]
Closing in favour of #249
